### ISSUE TITLE
Criteria for banner display too strict

### ISSUE THREAD

**Issue by code-tree** [slightlyoff/AppInstallImprovements#7] opened 2016-06-09 07:33 UTC
My app is currently working very well, and installs fine, though recently noticed it wasn't meeting Chrome's banner [display criteria](https://developers.google.com/web/updates/2015/03/increasing-engagement-with-app-install-banners-in-chrome-for-android?hl=en).

I simply have `{"display": "standalone"}` as the Web Manifest for DRY reasons. As for the other required fields:
- **short_name and name**: Auto-set from page's `<title>`, which is already updated based on language selection
- **icons**: Auto-set from `rel="icon"`
- **start_url**: Auto-set as is a single page app
- **service_worker**: Auto-set as registered on the page

Chrome's criteria is now forcing me to publish a new manifest for every language my app supports, despite the fact that Chrome could auto-set all this information as shown above. I understand the criteria is not set in stone, so this is simply feedback from my experience.

Thanks :)

**Comment by marcoscaceres** [comment] 2016-06-09 08:02
@code-tree, can we have the URL to your site so we can have a look? It doesn't seem to be there on the desktop version of https://codetree.com.au/

**Comment by benfrancis** [comment] 2016-06-09 10:23
It's interesting that you see the manifest as just a duplicate of page metadata, that isn't how I see it. Also the manifest allows you to apply the DRY principle by centralising the metadata rather than repeating it in the head of every single page.

You say your app is a single page web app, which may explain why you see the manifest as duplication. Are you sure you will always want to limit your app to just one page? URLs are the most powerful feature of the web.

Whilst the app name may have a fallback to the title of the current page, they are not the same thing. The web app name applies to the whole web app or website, whereas the title just applies to the current page. One website usually consists of many web pages which can have different titles (e.g. titles of articles in a news app or names of products in a shopping app).

Similarly the page icon may be used as a fallback to an app icon, but the page icon may be different for each page. An app icon defined in the manifest can have a defined scope of multiple web pages.

It's difficult for user agents to pick a good fallback for start_url, the current document URL is probably the best bet but it may not be the best page to start a web app at.

There is currently no service_worker property in the manifest.

I don't have any comments on Chrome's installability criteria which is up the Chrome team, but I wonder if maybe you're not getting the full benefits out of PWAs with your approach and that's why Chrome might not automatically promote it to users.

**Comment by benfrancis** [comment] 2016-06-09 10:24
It's interesting that you see the manifest as just a duplicate of page metadata, that isn't how I see it. Also the manifest allows you to apply the DRY principle by centralising the metadata rather than repeating it in the head of every single page.

You say your app is a single page web app, which may explain why you see the manifest as duplication. Are you sure you will always want to limit your app to just one page? URLs are the most powerful feature of the web.

Whilst the app name may have a fallback to the <title> of the current page, they are not the same thing. The web app name applies to the whole web app or website, whereas the <title> just applies to the current page. One website usually consists of many web pages which can have different titles (e.g. titles of articles in a news app or names of products in a shopping app).

Similarly the page icon may be used as a fallback to an app icon, but the page icon may be different for each page. An app icon defined in the manifest can have a defined scope of multiple web pages.

It's difficult for user agents to pick a good fallback for start_url, the current document URL is probably the best bet but it may not be the best page to start a web app at.

There is currently no service_worker property in the manifest.

I don't have any comments on Chrome's installability criteria which is up the Chrome team, but I wonder if maybe you're not getting the full benefits out of PWAs with your approach and that's why Chrome might not automatically promote it to users.

**Comment by code-tree** [comment] 2016-06-09 15:48
@benfrancis Those are some good points, thanks for clarifying. I can certainly see the benefits of manifests then.

I probably have a somewhat rare use case in that my app will be _very_ multi-lingual, but not large enough to warrant multiple pages (IMO). Therefore, I need multiple manifests, yet they don't add any value, and it further complicates my build scripts.

I was just thinking, having a SW + manifest file should be good enough to evidence that the site is trying to be a Web App. Adding additional restrictions seems to just further complicate the already complex infrastructure that is Web Apps and websites in general.

But I do understand the reasons for all this, so not a big deal I guess

**Comment by code-tree** [comment] 2016-06-10 06:08
@marcoscaceres This is a [demo version](https://stories.codetree.com.au) that doesn't have any content, so won't make much sense, but does demonstrate that it should really meet installability criteria but does not due to the manifest fields missing. Title is correctly set in either English or Korean when adding to home screen, depending on language being used.

@benfrancis Just realised the 'service_worker' property is only listed in [the explainer](https://github.com/slightlyoff/AppInstallImprovements/blob/master/explainer.md) of this repo (I guess it didn't get added in the end?). To clarify, manifest spec seems fine to me. Especially as Chrome auto-picks sensible defaults and doesn't require any fields to be set. But setting different criteria for the banner display effectively makes previously unrequired fields to be required.

**Comment by marcoscaceres** [comment] 2016-06-10 06:22
> @marcoscaceres This is a demo version that doesn't have any content, so won't make much sense, but does demonstrate that it should really meet installability criteria but does not due to the manifest fields missing. Title is correctly set in either English or Korean when adding to home screen, depending on language being used.

Ok, but the title needs to be set in the manifest - not just in the page... the page's title is different from the application's title (i.e., manifest's name or shortname). 

If you want to set it dynamically, you can either use as data URL as the src for the link rel=manifest or your can do manifest?lang=en (but there you need a different file).

**Comment by marcoscaceres** [comment] 2016-06-10 06:26
@code-tree, please see also:
- [Authority of the manifest metadata](http://www.w3.org/TR/appmanifest/#authority-of-the-manifest-s-metadata)
- [internationalization](http://www.w3.org/TR/appmanifest/#internationalization)

If you have suggestion for improvements to either, let me know 😸

**Comment by code-tree** [comment] 2016-06-10 16:10
> use as data URL

Great idea, thanks! For some reason the 'data' scheme didn't work (might be a Chrome bug) but the 'blob' scheme did, so I got it working.

**Comment by marcoscaceres** [comment] 2016-06-11 08:52
@mounirlamouri see above: Chrome bug not supporting data URLs for manifest? Reminds me I'm lacking a test for Gecko for that.

**Closed as completed** 2018-08-03 05:49 UTC
